### ISSUE TITLE
What about gpu inference time?

### ISSUE THREAD

**Issue by mahdip72** [snap-research/EfficientFormer#1]
Are there any experiments regarding the speed of efficientformer on gpu devices?

**Comment by edwardyehuang** [comment]
Same. Could you please provide ablation stuides that only use GPU/CPU on iPhone?

**Comment by liyy201912** [comment]
Thanks for your interest in our work. 

We are going to add the following speed results in the final manuscript: 
1. Speed on NVIDIA A100, deployed with TensorRT
2. Speed on Google 6, deployed with NNAPI
3. Speed on iPhone CPU, deployed with CoreML.

**Comment by alanspike** [comment]
Hi @edwardyehuang, with the latest iOS and Xcode, you could get the latency directly on CPU or CPU & GPU following this [link](https://developer.apple.com/videos/play/wwdc2022/10027/).
