### ISSUE TITLE
Latency results on Jetson Nano

### ISSUE THREAD

**Issue by tkupek** [snap-research/EfficientFormer#10]
My congratulations on this exciting contribution. I enjoyed the interesting read!

We are mainly working with Jetson Nano Edge devices, so I was curious how the latency of your ONNX models on TensorRT compares to the iPhone results.

Measurements were executed with the [NVIDIA trtexec benchmark](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#trtexec) on a Jetson Nano 4G devkit.

```
mobilenetv2-7.onnx
mean = 27.1622 ms

efficientformer_l1.onnx
mean = 57.412 ms

efficientformer_l3.onnx
mean = 145.45 ms
```

Do you have any intuition why the TensorRT benchmark performs this way? Is it because of the [limited GeLU support](https://github.com/NVIDIA/TensorRT/issues/1240) (you already mentioned this in the Limitations).

**Comment by tkupek** [comment]
Added a dump to show which layers take the most performance.

[efficienttransform-dump.txt](https://github.com/snap-research/EfficientFormer/files/8899806/efficienttransform-dump.txt)

**Comment by machineko** [comment]
@tkupek If you still looking into that your version of jetson nano have about 400 GFLOPs (0.4 TFLOPs) of performance and ANE in iphone 12 have 11 or 15 TFLOPs so 25-35x times more. Plus its build on maxwell architecture so it is 9 years old build on 28 nm it wont be comparable with modern neural co-processors in terms of latency and performance.

**Comment by tkupek** [comment]
Thanks a lot for your explanation, that makes sense!
I will try on a more modern Jetson NX with 21 TOPs and hope for an excellent performance of Nano Next 2023.

**Comment by hebangwen** [comment]
> Thanks a lot for your explanation, that makes sense! I will try on a more modern Jetson NX with 21 TOPs and hope for an excellent performance of Nano Next 2023.

Sorry to bother you after several years. I would like to know how the model performs at Jetson NX in your testing. Can it run under 50ms?

**Comment by tkupek** [comment]
Sorry @hebangwen, I have not done any further work on this and can't tell.

**Comment by hebangwen** [comment]
Copy. Thanks for your reply 🫡 @tkupek
