### ISSUE TITLE
How to apply MetaBlock3D to detection framework?

### ISSUE THREAD

**Issue by jinfagang** [snap-research/EfficientFormer#13]
HI, if I look it right, the 4 stages output shape would be something like this:

```
stage3 torch.Size([1, 448, 16, 16])
stage4 torch.Size([1, 448, 16, 16])
stage5 torch.Size([256, 1, 448])
```

now that the stage5 is 3 dimension, how should I using these output features to a FPN-like detection architecture?

**Comment by liyy201912** [comment]
Thanks for your interest in this work. 
Reshaping the feature of the 3D stage from [B, N, C] back to [B, C, H, W] format should work. 
The detection and segmentation codes are released, please refer to the implementations.
