### ISSUE TITLE
Question about the attention biases

### ISSUE THREAD

**Issue by SkeletonOne** [snap-research/EfficientFormer#19]
Hi, thanks for your great work. I wonder how to fine-tune the model to object detection, as the attention biases in Imagenet classification have small resolutions, while the shapes are different in object detection. I notice you use interpolation for the biases here, but do they need to be re-initialized and train from scratch for object detection?

**Comment by liyy201912** [comment]
Hi, yes you're correct, to adapt EfficientFormer to a different resolution, say from 224 in classification to 512/1024/2048 in segmentation and detection, the attention biases are re-initialized and directly trained with the target resolution.

**Comment by SkeletonOne** [comment]
Thanks for your reply!
