### ISSUE TITLE
compare inference time with swin-tiny on gpu 

### ISSUE THREAD

**Issue by StockDrivenAI** [snap-research/EfficientFormer#2]
Swin-Tiny contains 29M parameters got 81.3% Top-1 .
EfficientFormer-L3 contains 31.3M parameters got 82.4% Top-1 .

Anyway, I think once if the code is open-source, we can easily compare the two models.

**Comment by liyy201912** [comment]
We make a simple test on NVIDIA 2080Ti, Swin-Tiny runs at 1093 img/s, while EfficientFormer-L3 at 1106 img/s.

**Comment by StockDrivenAI** [comment]
Great ! Thank your for the information.
