### ISSUE TITLE
RuntimeError: Unknown model (efficientformer_l1)

### ISSUE THREAD

**Issue by Jialeen** [snap-research/EfficientFormer#21]
I run the code on my computer without GPU, but the error happens at creating model: RuntimeError: Unknown model (efficientformer_l1). The versions of  torch, timm, and submitit are 1.8.0+cpu, 0.6.7 and 1.4.5.  

Thank you very much.

**Comment by liyy201912** [comment]
I'm not quite certain about this issue. Perhaps
1. It is because the CPU version of PyTorch, 
2. It is because some packages are not properly installed (such as timm)

Could you share the detailed log?

**Comment by Jialeen** [comment]
> 

The detailed log is as follows:
![1660007295703](https://user-images.githubusercontent.com/33652291/183540731-873b70c6-5bdb-4fc7-a8cc-d414bd002d68.png)
Thank you very much!

**Comment by liyy201912** [comment]
It seems that you are using a new script `Demo.py`, did you import the EfficientFormer models in that script? 
Similar to `main.py`: 
```
from models import *
```
