### ISSUE TITLE
can't convert to coreml

### ISSUE THREAD

**Issue by rotem154154** [snap-research/EfficientFormer#22]
when i try to convert to coreml i get ValueError: node input.19 (gelu) got 2 input(s), expected [1]
im using pytorch version 1.12.0 and coremltools version 5.2.0

**Comment by liyy201912** [comment]
I can reproduce the bug with latest PyTorch. 

```
WARNING:root:Torch version 1.13.0a0+08820cb has not been tested with coremltools. You may run into unexpected errors. Torch 1.10.2 is the most recent version that has been tested.
...
...
ValueError: node input.21 (gelu) got 2 input(s), expected [1]
```

I guess this bug is introduced by latest PyTorch updates. PyTorch <= 1.11 works for me.
