### ISSUE TITLE
segmentation is not correct

### ISSUE THREAD

**Issue by yeyan00** [snap-research/EfficientFormer#26]
segmentation use script,config fpn_efficientformer_l1_ade20k_40k.py
![image](https://user-images.githubusercontent.com/8616560/187184932-8cf1e461-1c66-427d-9cbd-9f14d3f69a1a.png)

**Comment by liyy201912** [comment]
Hi, could you provide more details?
1. Is the pretrained model successfully (and fully) loaded? Maybe you can first verify mIoU on ADE20K to check. 
2. If so, have you ever tested other scenes? For example, some indoor images?

**Comment by yeyan00** [comment]
dataset use mapillary

**Comment by alanspike** [comment]
Hi @yeyan00 , did you train the model on your own dataset or use the pre-trained model from ADE20K on your dataset?

**Comment by alanspike** [comment]
Hi @yeyan00, I'll close the issue for now. Please feel free to open it if you'd like to discuss more about the model/dataset training. Thanks.
