### ISSUE TITLE
Fine-tuning with more patches/higher resolution

### ISSUE THREAD

**Issue by rotem154154** [snap-research/EfficientFormer#29]
is there any way to take the pretrained models you provided and continue training them on larger resolution?

**Comment by liyy201912** [comment]
The main problem is fixed-resolution position embedding (attention bias), but you can simply migrate to flexible resolution by interpolation, as in detection and segmentation: 

https://github.com/snap-research/EfficientFormer/blob/edbc27ceec7e0b429492bc5ea2afbef1bdb09bb2/segmentation/backbone.py#L96)
