### ISSUE TITLE
Is there any experimental accuracy without distillation training？

### ISSUE THREAD

**Issue by zhangyubo0722** [snap-research/EfficientFormer#31]
Hello, I see that the accuracy in your paper is the result of using distillation training. Is there any experimental accuracy without distillation training?

**Comment by alanspike** [comment]
Hi @zhangyubo0722, thanks for your interests. We didn't train the model w/o distillation. However, there is some discussion [here](https://github.com/snap-research/EfficientFormer/issues/15#issuecomment-1248671052) for the model performance w/o distillation. Hope it would help.
