### ISSUE TITLE
Can't convert EfficientFormer v2 to coreml

### ISSUE THREAD

**Issue by rotem154154** [snap-research/EfficientFormer#36]
when trying to convert efficientformerv2_l model to coreml i get the error:
PyTorch convert function for op 'bernoulli_' not implemented.

I can convert the first version of efficientFormer.
i'm using pytorch 1.11.0, coremltools version 6.1

**Comment by liyy201912** [comment]
Hi, 

Pytorch 1.11 + CoreML 5.2 works for me. Seems there are some conflicts/deprecated features in CoreML 6.1 and the latest pytorch (1.12 or 1.13)
