### ISSUE TITLE
Adding EfficientFormer to the transformers library

### ISSUE THREAD

**Issue by alaradirik** [snap-research/EfficientFormer#37]
Hi,

I'm a machine learning engineer at 🤗 Hugging Face and we are about to add EfficientFormer to [Transformers](https://github.com/huggingface/transformers.git) with this [PR](https://github.com/huggingface/transformers/pull/20459) by two community members. 

We are really excited to add this work to our library and wanted to ask if you would be interested in creating a Snap Research organisation on the hub, such that we can store all model checkpoints there (rather than under the _huggingface_ organization)?

As you may or may not know, each model on the HuggingFace [hub](https://huggingface.co/) has its own Github repository where we store configuration files, the converted weights of the model and a README, see an example repo over [here](https://huggingface.co/google/vit-base-patch16-224).

Please let me know!

Kind regards,
Alara
ML Engineer @ HuggingFace

**Comment by alanspike** [comment]
Hi @alaradirik,

Thanks for helping add the EfficientFormer to the transformer library. We will discuss about adding the Snap Research organization to Hugging Face and let you know. Also, we have a recent work, EfficientFormer V2, with code/model released that further improves the model performance.

**Comment by alaradirik** [comment]
Hi @alanspike,

We would be happy to add EfficientFormer V2 to the library as well, looking forward to hearing back from you!

**Comment by alanspike** [comment]
Hi @alaradirik,
Thanks for adding the EfficientFormerV2 to the library! We have created a Snap Research organization at HuggingFace [here](https://huggingface.co/snap-research).

**Comment by alaradirik** [comment]
Hi @alanspike, that's great. We are adding EfficientFormer V1 but we are planning to add EfficientFormer V2 as well.

We are about to merge the PR, we will transfer the repos to the Snap Research organization shortly.
