### ISSUE TITLE
Could you please provide pytorch to onnx/coreml conversion code?

### ISSUE THREAD

**Issue by zijunwei** [snap-research/EfficientFormer#38]
I got some errors converting the efficient-former-v2-s2 model to coreml (bicubic resizing not supported) and very different inference time. 
Could you please share the code you used for model conversion? (both to coreml and onnx if possible)
Thanks in advance!

**Comment by leonid-pishchulin** [comment]
+1 on that

**Comment by liyy201912** [comment]
Hi, 

The feature is added. 

A quick note, pytorch 1.11 & coreML 5.2 work well for me. I do heard there are some bugs in their latest releases (pytorch 1.13 & coreml 6.1)
