### ISSUE TITLE
EfficientFormerV2-S0/S1 checkpoints links are broken

### ISSUE THREAD

**Issue by leonid-pishchulin** [snap-research/EfficientFormer#40]
I cannot download pytorch model weights for EfficientFormerV2-S1

**Comment by leonid-pishchulin** [comment]
same for EfficientFormerV2-S0

**Comment by liyy201912** [comment]
Hi Leonid, 

I re-downloaded and tested it, and it seems fine. (There should be a download button on the right top of the google drive page)

**Comment by leonid-pishchulin** [comment]
I see, thanks ! missed that part, as other checkpoints were opening with the large download button in the center of the page
