### ISSUE TITLE
efficientformer_v2.py have a bug

### ISSUE THREAD

**Issue by jnulzl** [snap-research/EfficientFormer#41]
https://github.com/snap-research/EfficientFormer/blob/4e273afc8f1d68d2ceb5bb8e7526476f523057ac/models/efficientformer_v2.py#L643

this line  should be :

```python
cls_out = self.head(x.flatten(2).mean(-1))
```

**Comment by Andy-Dang12** [comment]
i forward efficientformerv2_s0 and i found a bug
`RuntimeError: mat1 and mat2 shapes cannot be multiplied (176x7 and 176x1000)`

```
import torch
from torchinfo import summary
from timm.models import create_model
from models import *

model = create_model(
        'efficientformerv2_s0',
        num_classes=1000,
        distillation=True, #!args.distillation_type != 'none'
        pretrained='eformer_s0_450.pth',
        fuse=False          #!args.eval
        )
inp = torch.full((1, 3, 224, 224), fill_value=0.6, dtype=torch.float32, device='cuda:0')
out = model(inp)
print(out)

```

**Comment by liyy201912** [comment]
Thanks for reporting the bug. It is due to some inherited code chunk from EfficientFormer-V1, and it's fixed now.
