### ISSUE TITLE
EfficientFormerv2 how to train other resolution 

### ISSUE THREAD

**Issue by jnulzl** [snap-research/EfficientFormer#44]
EfficientFormerv2 how to train other resolutio, such as: 64x64,  112x112, ....
I found a similarly issue #20 and try it , but is invalid

**Comment by jnulzl** [comment]
resolved!

**Comment by SeheeKim618** [comment]
Hi, how did you solve it?
I tried #20 too, but it didn't work :(

**Comment by Learner-feng** [comment]
May I ask how you solved it and what parameters you modified?

**Comment by chinmayjog13** [comment]
What value did you set the resolution in attention module to for what input resolution?
