### ISSUE TITLE
Model release

### ISSUE THREAD

**Issue by rotem154154** [snap-research/EfficientFormer#6]
Thanks for sharing your work with us.
Can you update on the code release?
Also the pytorch models are weights only and can't be opened with torch.load() without the code of the model, so if the code release is delaying can you share the models in a way we can load them? 
Thanks

**Comment by liyy201912** [comment]
Thanks for your interest in this work. Yes, we are only releasing the CoreML model for speed verification at this time. Full definition & training code will hopefully be released in 1-2 weeks, please stay tuned!
